### ISSUE TITLE
Make Version Numbering Consistent

### ISSUE THREAD

**Issue by scientiac** [dagmawibabi/ScholArxiv#8]
![Screenshot_20240811-150200](https://github.com/user-attachments/assets/eba6cfbe-8641-460f-8ef0-b23dbbef35d3)

I have v2.0.0 installed but Obtainium shows version 1.0.0 being installed and says v2.0.0 is the latest version. The versioning on the app shows 1.0.0 but in GitHub it shows v2.0.0. It'll be easier to download/update via Obtainium Package Manager if the version numbers are consistent everywhere.

**Comment by dagmawibabi** [comment]
Hey thank you so much and the issue is now fixed.
Try again and tell me how it foes so I can close this issue.

**Comment by ramanveerji** [comment]
> Hey thank you so much and the issue is now fixed.
> Try again and tell me how it foes so I can close this issue.

Bro you have to build the apk again. Whenever you release an apk edit those 2 lines in build gradle then release.

**Comment by dagmawibabi** [comment]
Yeah and that's what I did, check the release page and redownload maybe

**Comment by ramanveerji** [comment]
> Yeah and that's what I did, check the release page and redownload maybe

![Screenshot_2024-08-14-21-29-31-822_com.miui.packageinstaller.png](https://github.com/user-attachments/assets/fd4f5df8-360e-42f8-b5c5-7b29fc0612c1)

I downloaded it from obtainium. You need to sync build gradle then release bro. Application version is still 1.0.0 it should be 2.0.0

**Comment by scientiac** [comment]
I installed the latest app and the issue still remains. You should maybe change the version in 'pubspec.yaml' (I am no flutter dev, just guessing)

![Screenshot_20240814-214300](https://github.com/user-attachments/assets/71ea7f0c-db66-4078-9cfd-f32b5e4282ba)

also, you might want to change the release name to just 2.0.0 instead of v2.0.0 on github itself as well.
